version: "3.9"
services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: "attestation02"
      POSTGRES_USER: "attestation02"
      POSTGRES_PASSWORD: "attestation02"
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql

volumes:
  pg_volume: